### ISSUE TITLE
Doesn't work. Tried to achieve the same using "Flex 2".

### ISSUE THREAD

**Issue by piejanssens** [nicolas17/yeloenable#1]
deviceIsJailbroken => return FALSE
isRootedTest => return TRUE/FALSE

Tested these settings using Flex 2, but kept getting "There is a streaming problem."

**Comment by nicolas17** [comment]
I wrote this completely blind, without testing it with the real app. The person I wrote it for also reported that the app doesn't complain about it being jailbroken anymore, but doesn't allow streaming either.
